[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/questions"
  to = "/.netlify/functions/questions"
  status = 200

[[redirects]]
  from = "/api/questions/*"
  to = "/.netlify/functions/questions/:splat"
  status = 200

[[redirects]]
  from = "/api/answers/*"
  to = "/.netlify/functions/answers/:splat"
  status = 200

[[redirects]]
  from = "/api/notes"
  to = "/.netlify/functions/notes"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
